version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tabletap-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://your_user:your_pass@cluster.mongodb.net/tabletap
      - JWT_SECRET=your_jwt_secret
    restart: always

  frontend:
    build: ./frontend
    container_name: tabletap-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
